name: sedarp
description: "SEDARP - Serviço de Sedação Ambulatorial em Regime de Pequena Cirurgia"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI e Icons
  cupertino_icons: ^1.0.8
  
  # Gerenciamento de Estado
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  
  # Utilitários
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true 